### ISSUE TITLE
Block textures dont render as golden?

### ISSUE THREAD

**Issue by hyperdotbat** [Darkhax-Minecraft/Gilded-Sherds#2] opened 2024-01-16 18:09 UTC
![image](https://github.com/Darkhax/Gilded-Sherds/assets/48921794/30672240-fbb3-4c01-8409-83c9450b60ac)

**Comment by Darkhax** [comment] 2024-01-16 18:13
That's a very weird issue. The renderer for the held item is the same as the in-world renderer so it should be working fine. What version of the game, mod, and modloader are you using?

**Comment by hyperdotbat** [comment] 2024-01-16 18:15
Im on 1.20.1 Fabric 0.15.3 (Fabric API 0.91.0) and the mod's ver is 1.0.2

**Comment by Darkhax** [comment] 2024-01-16 18:25
The mod seems to be working just fine with those versions. I am guessing one of the other mods you have may be causing this issue? Are you sure the pot in the world is the same as the one in your hand? 
![image](https://github.com/Darkhax/Gilded-Sherds/assets/2250798/e3ceb64a-ca97-4ac9-9d3c-1f5411c9ea7e)

**Comment by hyperdotbat** [comment] 2024-01-16 18:45
Yeah now I see its quite bizarre it works for one but not the other suddenly, probably other mods causing some issues but not sure
![image](https://github.com/Darkhax/Gilded-Sherds/assets/48921794/cad3d8c2-19a9-4a7d-bb3f-50611baa6f8c)
![image](https://github.com/Darkhax/Gilded-Sherds/assets/48921794/47531f88-08e9-4f3b-91e7-56c3087d05e4)

**Comment by Darkhax** [comment] 2024-01-16 18:51
Okay, well let me know if you can find out which mod is causing it. I would recommend creating a new profile with only Gilded Sherds and Fabric API first to make sure it's not something else.

**Comment by Darkhax** [comment] 2024-02-07 04:46
Closing this issue for now as the issue could not be reproduced. If you have any more info in the future feel free to create a new issue.

**Closed as completed by Darkhax** 2024-02-07 04:46 UTC
Labels: unverified
